version: '3.4'

services:
  asp-net:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: SuperPassword123
      ACCEPT_EULA: "Y"